version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    assignees:
      - 'andreasremdt'
    reviewers:
      - 'andreasremdt'
    commit-message:
      prefix: 'deps'
    open-pull-requests-limit: 10
